### PR TITLE
Added mangos user creation to InstallDatabases.bat

### PR DESCRIPTION
**Pull request by tbayart**
Updated InstallDatabases.bat with mangos user creation and privileges granting

---
This change is [Reviewable](https://reviewable.io/reviews/mangostwo/database/96)

### CODE REVIEW

**Comment by billy1arm** [comment]
@tbayart - very nice, however there is a problem with mangosCreateUser.sql 
the databases can be renamed and this file assumes that the databases are using the set names.

If this can be done via the MySQL commandline, then it can be included in the main script which can use variable substitution to use the correct database names.

**Comment by tbayart** [comment]
Good point, I will check that

**Comment by tbayart** [comment]
I commited an update with the requested fix

**Comment by billy1arm** [comment]
@tbayart - awesome work

The only thing that jumped out at me was maybe the option for the user to specify the account name to add, rather than mangos.

My apologies for not spotting it before

**Pull request merged**
